/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/rock_photogrammetry_scan.glb -o ./src/components/RockModel.tsx --types 
Author: GSXNet (https://sketchfab.com/gsxn)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/rock-photogrammetry-scan-872fa4d23b04436ba476041bae68b46d
Title: Rock Photogrammetry Scan
*/

"use client";

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root']: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/rock_photogrammetry_scan.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/rock_photogrammetry_scan.glb')
